### ISSUE TITLE
Not really an issue, but diff color schemes

### ISSUE THREAD

**Issue by crocodileDundee** [idleberg/Hopscotch#5]
Hi, I don't think this is really an issue, but I just noticed that Hopscotch color scheme changes from Notepad++ to Visual Studio to Gedit. Those are the only ones I've spotted, since they are the ones I use.
Just to let you know =)

**Comment by idleberg** [comment]
Thanks, I'm aware to this and would prefer more consistent themes myself. Hopscotch is built using [base16-builder](https://github.com/chriskempson/base16-builder), and I'm not sure if Chris put focus on consistency (also, many templates are user-contributed.)

**Comment by idleberg** [comment]
However, I guess it's a good idea to mention the inconsistencies in the README and will do just that when I get to it.

**Comment by me-stevens** [comment]
Ok, no prob. This is one of the themes that I've known of so far that supports an insane number of editors anyway, so no complains  :+1: 
Thank you for your work!
