### ISSUE TITLE
Workbench Theming for VS Code

### ISSUE THREAD

**Issue by ajitid** [idleberg/Hopscotch#6]
Will you do it?

**Comment by idleberg** [comment]
I have not the faintest idea what you're talking about

**Comment by ajitid** [comment]
😂😂 Now you can even theme workbench (editor itself) of VS Code. Will you do it for Hopscotch theme.

**Comment by idleberg** [comment]
I don't think so. Hopscotch is a syntax theme and I don't use VS Code personally.

**Comment by ajitid** [comment]
Sublime?
