### ISSUE TITLE
Font?

### ISSUE THREAD

**Issue by tleb** [idleberg/Hopscotch#7]
Sorry to open an issue for this, but what font are you using in the preview? I can't get those same, vibrant colour and I think the font is what differs.

Thanks!

**Comment by idleberg** [comment]
I probably used [Fira Mono](https://mozilla.github.io/Fira/) for the screenshots. As for the colors, they might differ depending on your editor and the used syntax highlighter. The theme was created with base16-builder, so the screenshot comes from it's [preview template](https://chriskempson.github.io/base16/).
